import { ProposedPatch } from "../agent/types";
import { colors } from "../colors";

export interface PRDetails {
  title: string;
  branch: string;
  body: string;
  qodoCommands: string[];
}

export class PRManager {
  /**
   * Generates a complete PR description with automated Qodo review integration
   */
  public generatePR(runId: string, errorSummary: string, patches: ProposedPatch[]): PRDetails {
    const branch = `fix/autofix-ci-run-${runId}`;
    const title = `fix(ci): automatically resolve test failure in run #${runId}`;

    const diffSections = patches
      .map(
        (p) => `### 📄 \`${p.filePath}\`\n**Explanation:** ${p.explanation}\n\`\`\`diff\n${p.diffSummary}\n\`\`\``
      )
      .join("\n\n");

    const body = `## 🤖 AutoFix-Agent Autonomous Remediation

### 🎯 Overview
This Pull Request was autonomously generated by **AutoFix-Agent** running on the **TrueForge Agent Harness** in response to failed CI/CD workflow run **#${runId}**.

### 🔍 Root Cause Analysis
- **Failure Detected:** \`${errorSummary}\`
- **Sandbox Verification:** Reproduced locally and verified green before opening this PR.

### 🛠️ Applied Patches
${diffSections}

---

### 🧪 Automated Quality Review Triggered
> CC: @qodo-merge-bot

/describe
/review
/improve
`;

    return {
      title,
      branch,
      body,
      qodoCommands: ["/describe", "/review", "/improve"],
    };
  }

  public logPRCreated(pr: PRDetails) {
    console.log(colors.green(colors.bold(`\n🎉 [Pull Request Created Successfully]`)));
    console.log(colors.cyan(`Branch: ${pr.branch}`));
    console.log(colors.cyan(`Title:  ${pr.title}`));
    console.log(colors.magenta(`Qodo Review Commands Triggered: ${pr.qodoCommands.join(", ")}`));
  }
}
